### ISSUE TITLE
Bin2C adds garbage to output array

### ISSUE THREAD

**Issue by armornick** [gwilymk/bin2c#3]
I've done a few tests with bin2c and I've come to the conclusion that the program adds an unnecessary extra byte to output array.

The cause of this is found in bin2c.c on line 50: `file_size++;`

This line increment is unnecessary since `ftell` gets the complete size in bytes and no additional memory is necessary. In addition, `fread` will not read past the end-of-file marker so the allocated buffer retains whatever garbage it contained at the time of allocation.

**Comment by gwilymk** [comment]
Thanks for the bug report, I've fixed it and added some tests so hopefully something like this doesn't happen again.
