### ISSUE TITLE
How to compile with bz2?

### ISSUE THREAD

**Issue by Diversus23** [gwilymk/bin2c#4]
It's a good job, but I would like to have the ability to compile c bz2 attached to your distribution.

**Comment by gwilymk** [comment]
Have you tried compiling with USE_BZ2 defined? On unix it'll be something along the lines of:
```sh
gcc -o bin2cbz2 bin2c.c -DUSE_BZ2 -lbz2
# or
clang -o bin2cbz2 bin2c.c -DUSE_BZ2 -lbz2
```

**Comment by gwilymk** [comment]
Closed due to no response from reporter.
